name: Continuous Integration
permissions:
  contents: read

on:
  push:
    branches:
      - master
      - release/**

    paths-ignore:
      - '.github/**'
      - 'doc/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    
    - name: Restore dependencies (dotnet restore)
      run: dotnet restore
      working-directory: src
      
    - name: Build (dotnet build)
      run: dotnet build --configuration release --no-restore
      working-directory: src
      
    - name: Test (dotnet test)
      run: dotnet test --configuration release --no-build --verbosity normal
      working-directory: src